#!/bin/sh

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources

export XKL_XMODMAP_DISABLE=1

xsetroot -solid grey
vncconfig -iconic &
x-window-manager &

gnome-panel &
gnome-settings-daemon &
metacity &
nautilus -n &

gconftool-2 -t str -s /apps/metacity/global_keybindings/show_desktop ""

#gnome-terminal &
virt-manager &
